<?php $abia = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',1)->count(); ?>
<?php $adamawa = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',2)->count(); ?>
<?php $akwa_ibom = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',3)->count(); ?>
<?php $anambra= \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',4)->count(); ?>
<?php $bauchi = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',5)->count(); ?>
<?php $bayelsa = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',6)->count(); ?>
<?php $benue = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',7)->count(); ?>
<?php $borno = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',8)->count(); ?>
<?php $cross_river = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',9)->count(); ?>
<?php $delta = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',10)->count(); ?>
<?php $ebonyi = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',11)->count(); ?>
<?php $edo = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',12)->count(); ?>
<?php $ekiti = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',13)->count(); ?>
<?php $enugu = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',14)->count(); ?>
<?php $FCT= \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',15)->count(); ?>
<?php $gombe = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',16)->count(); ?>
<?php $imo = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',17)->count(); ?>
<?php $jigawa = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',18)->count(); ?>
<?php $kaduna = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',19)->count(); ?>
<?php $kano = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',20)->count(); ?>
<?php $katsina = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',21)->count(); ?>
<?php $kebbi = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',22)->count(); ?>
<?php $kogi = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',23)->count(); ?>
<?php $kwara= \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',24)->count(); ?>
<?php $lagos = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',25)->count(); ?>
<?php $nasarawa = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',26)->count(); ?>
<?php $niger = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',27)->count(); ?>
<?php $ogun = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',28)->count(); ?>
<?php $ondo = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',29)->count(); ?>
<?php $osun = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',30)->count(); ?>
<?php $oyo = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',31)->count(); ?>
<?php $plateau = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',32)->count(); ?>
<?php $rivers = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',33)->count(); ?>
<?php $sokoto = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',34)->count(); ?>
<?php $taraba = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',35)->count(); ?>
<?php $yobe = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',36)->count(); ?><
<?php $zamfara = \App\fellowshipapplication::innerjoin('states','states.state_id','=','fellowshipapplications.state')->where('completed','=',1)->where('rating_level','=',2)->where('state','=',37)->count(); ?>